In [22]:
import numpy as np
import pandas as pd
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook()


Loading BokehJS ...

In [62]:
V=np.load("2025-01-24_11-42-45/v_table.npy")

In [8]:
pwd

'/home/jet08013/GitHub/RLKaraDogan'

In [10]:
V

array([-3.00896845, -2.86066779, -2.07570926, -1.83071161, -1.36825418,
       -1.37755469, -1.40055623, -0.88794818, -0.90437999, -0.73917228,
       -0.69153731, -0.62337682, -0.71346183, -0.55289102, -0.50698427,
       -0.37424128, -0.48615138, -0.5683024 , -0.44678971, -0.39742407,
       -0.57384037, -0.6775794 , -0.81151418, -0.8529733 , -1.05327751,
       -1.12024404, -1.47102732, -1.62233997, -2.03714565, -2.28668377,
       -2.89429955, -3.49611483, -3.83125273, -4.27118737, -4.54318259,
       -4.44749383, -4.41306962, -5.65006614, -4.37441056,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [11]:
np.argmin(V)

np.int64(37)

In [12]:
Q = np.load("2025-01-24_10-43-56/q_table.npy")

In [13]:
Q

array([[-2.06870773e+01, -1.98515390e+01, -2.12763422e+01, ...,
        -2.02043231e+01, -1.73643757e+01, -2.10015009e+01],
       [-2.28770395e+01, -2.33688413e+01, -2.28870026e+01, ...,
        -2.32069737e+01, -2.37390145e+01, -2.25585017e+01],
       [-2.28166215e+01, -2.24865707e+01, -2.33358583e+01, ...,
        -2.19817760e+01, -2.12516684e+01, -2.22886828e+01],
       ...,
       [ 2.15756674e-02,  2.37797087e-01,  7.69531677e-01, ...,
         2.30769887e-01,  7.86303664e-01,  4.04824999e-01],
       [ 3.08866911e-02,  6.19564520e-01,  8.25361812e-01, ...,
         4.51476665e-01,  2.19088568e-01,  2.27035462e-01],
       [ 1.29795628e-01,  9.31095617e-01,  1.88395033e-01, ...,
         9.51339361e-01,  8.08109201e-01,  3.09786562e-01]],
      shape=(100, 20))

In [14]:
Q[0,:]

array([-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
       -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
       -20.37763871, -20.36501242, -21.50438801, -20.08815177,
       -19.50730511, -21.05554728, -21.15359243, -20.23519153,
       -20.34827178, -20.20432314, -17.36437575, -21.0015009 ])

In [15]:
Q[1,:]

array([-22.87703945, -23.36884132, -22.8870026 , -22.65544912,
       -23.53497417, -23.1681665 , -23.36517685, -24.30698574,
       -23.29899101, -23.64365848, -22.738666  , -23.69039222,
       -23.4665515 , -23.18631346, -23.72887776, -16.92027895,
       -22.50239792, -23.20697371, -23.73901454, -22.55850171])

In [16]:
Q[2,:]


array([-22.81662149, -22.48657065, -23.3358583 , -23.25000917,
       -22.85696733, -21.22989911, -21.51833406, -22.18609773,
       -21.5470101 , -22.18615072, -22.48929432, -15.9494979 ,
       -22.83861935, -21.73843565, -22.40872264, -22.90048959,
       -22.16329022, -21.981776  , -21.25166842, -22.28868283])

In [17]:
Q[3,:]

array([-22.29355892, -21.43661523, -22.67930788, -23.16912126,
       -22.14902855, -21.91283999, -22.52145395, -22.58799361,
       -21.64390648, -21.92705447, -22.66752363, -22.05289031,
       -22.1237351 , -20.93944104, -22.42862801, -22.38802179,
       -22.64639978, -22.70305336, -15.66763492, -21.621998  ])

In [18]:
Q[4,:]

array([-20.01474193, -20.5843127 , -21.58415684, -21.48262496,
       -20.64728693, -21.28286572, -21.46927243, -21.28944664,
       -20.76901498, -21.67342716, -21.43922732, -14.83667392,
       -21.08221136, -20.54385467, -21.28441429, -20.9058065 ,
       -21.45099525, -21.83196056, -21.22293376, -21.36591028])

In [19]:
Q[5,:]

array([-20.13840827, -20.61286218, -21.19249567, -20.35821474,
       -20.84417665, -19.46841693, -20.78109164, -20.39444746,
       -21.36195025, -20.51995212, -21.18401669, -21.2106217 ,
       -20.33917858, -14.82117947, -21.2852823 , -19.96596957,
       -21.16137438, -19.83842387, -19.74091647, -21.19908075])

In [20]:
np.argmax(Q[0,:])

np.int64(18)

In [26]:
M=np.argmax(Q,axis=1)


In [27]:
F=figure()
F.line(list(range(100)),M)
show(F)

In [28]:
Q.sum(axis=1)

array([-408.43954357, -458.84425301, -439.42399559, -437.56020626,
       -416.76113818, -406.41805969, -401.77055204, -391.89239657,
       -377.93926922, -365.53419424, -364.94925578, -355.46738394,
       -356.01317813, -353.70162336, -348.71781054, -344.51707622,
       -337.5861818 , -337.77130792, -333.28645836, -332.30589872,
       -328.06720686, -331.89338398, -332.18517299, -331.77878625,
       -334.89717474, -338.78815982, -342.52157007, -347.87153833,
       -357.67797757, -375.93496005, -382.28978728, -398.81521488,
       -406.94734854, -431.02461693, -437.75202985, -464.84577011,
       -466.57252973, -481.50392648, -487.39786506,   12.1529854 ,
          8.11448002,   11.30297589,    9.5918462 ,    8.35221824,
          7.55924081,    9.94414073,   10.87290959,   11.56872738,
         11.66775103,    8.575761  ,    9.05287078,    9.62040584,
         10.75344587,    8.44059204,   10.69120451,    7.29941666,
         10.54615135,    9.93285257,   11.20365689,   10.76862

In [29]:
Q.shape

(100, 20)

In [30]:
Q

array([[-2.06870773e+01, -1.98515390e+01, -2.12763422e+01, ...,
        -2.02043231e+01, -1.73643757e+01, -2.10015009e+01],
       [-2.28770395e+01, -2.33688413e+01, -2.28870026e+01, ...,
        -2.32069737e+01, -2.37390145e+01, -2.25585017e+01],
       [-2.28166215e+01, -2.24865707e+01, -2.33358583e+01, ...,
        -2.19817760e+01, -2.12516684e+01, -2.22886828e+01],
       ...,
       [ 2.15756674e-02,  2.37797087e-01,  7.69531677e-01, ...,
         2.30769887e-01,  7.86303664e-01,  4.04824999e-01],
       [ 3.08866911e-02,  6.19564520e-01,  8.25361812e-01, ...,
         4.51476665e-01,  2.19088568e-01,  2.27035462e-01],
       [ 1.29795628e-01,  9.31095617e-01,  1.88395033e-01, ...,
         9.51339361e-01,  8.08109201e-01,  3.09786562e-01]],
      shape=(100, 20))

In [31]:
Q[0,:]

array([-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
       -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
       -20.37763871, -20.36501242, -21.50438801, -20.08815177,
       -19.50730511, -21.05554728, -21.15359243, -20.23519153,
       -20.34827178, -20.20432314, -17.36437575, -21.0015009 ])

In [32]:
Q[40,:]

array([0.68728021, 0.01772079, 0.1670723 , 0.32405752, 0.58008602,
       0.22569301, 0.42801793, 0.28474428, 0.05371894, 0.01006334,
       0.74083794, 0.23777004, 0.20284712, 0.61080362, 0.67638682,
       0.70471464, 0.10940745, 0.45562513, 0.95944176, 0.63819116])

In [33]:
Q[39,:]

array([0.95787313, 0.85451446, 0.05936064, 0.98883767, 0.89834882,
       0.46214895, 0.71677387, 0.95720086, 0.5701168 , 0.28326369,
       0.39186757, 0.91206682, 0.8323686 , 0.41724801, 0.7595498 ,
       0.30361303, 0.10684751, 0.65988396, 0.89245009, 0.12865111])

In [34]:
Q[38,:]

array([-24.40414987, -23.76704432, -26.07522408, -24.67660041,
       -26.45197656, -24.43972346, -24.80433252, -25.19927854,
       -23.88707506, -19.3304873 , -24.39836156, -23.7413513 ,
       -24.5391804 , -23.78742239, -23.95855727, -24.82344543,
       -25.10761341, -25.10339664, -23.78251609, -25.12012845])

In [35]:
Q[0,:]

array([-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
       -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
       -20.37763871, -20.36501242, -21.50438801, -20.08815177,
       -19.50730511, -21.05554728, -21.15359243, -20.23519153,
       -20.34827178, -20.20432314, -17.36437575, -21.0015009 ])

In [36]:
Q[:40,:]

array([[-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
        -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
        -20.37763871, -20.36501242, -21.50438801, -20.08815177,
        -19.50730511, -21.05554728, -21.15359243, -20.23519153,
        -20.34827178, -20.20432314, -17.36437575, -21.0015009 ],
       [-22.87703945, -23.36884132, -22.8870026 , -22.65544912,
        -23.53497417, -23.1681665 , -23.36517685, -24.30698574,
        -23.29899101, -23.64365848, -22.738666  , -23.69039222,
        -23.4665515 , -23.18631346, -23.72887776, -16.92027895,
        -22.50239792, -23.20697371, -23.73901454, -22.55850171],
       [-22.81662149, -22.48657065, -23.3358583 , -23.25000917,
        -22.85696733, -21.22989911, -21.51833406, -22.18609773,
        -21.5470101 , -22.18615072, -22.48929432, -15.9494979 ,
        -22.83861935, -21.73843565, -22.40872264, -22.90048959,
        -22.16329022, -21.981776  , -21.25166842, -22.28868283],
       [-22.29355892, -21.43661523, -

In [37]:
Q[:39,:]

array([[-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
        -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
        -20.37763871, -20.36501242, -21.50438801, -20.08815177,
        -19.50730511, -21.05554728, -21.15359243, -20.23519153,
        -20.34827178, -20.20432314, -17.36437575, -21.0015009 ],
       [-22.87703945, -23.36884132, -22.8870026 , -22.65544912,
        -23.53497417, -23.1681665 , -23.36517685, -24.30698574,
        -23.29899101, -23.64365848, -22.738666  , -23.69039222,
        -23.4665515 , -23.18631346, -23.72887776, -16.92027895,
        -22.50239792, -23.20697371, -23.73901454, -22.55850171],
       [-22.81662149, -22.48657065, -23.3358583 , -23.25000917,
        -22.85696733, -21.22989911, -21.51833406, -22.18609773,
        -21.5470101 , -22.18615072, -22.48929432, -15.9494979 ,
        -22.83861935, -21.73843565, -22.40872264, -22.90048959,
        -22.16329022, -21.981776  , -21.25166842, -22.28868283],
       [-22.29355892, -21.43661523, -

In [39]:
Q[:39,:].sum(axis=1)

array([-408.43954357, -458.84425301, -439.42399559, -437.56020626,
       -416.76113818, -406.41805969, -401.77055204, -391.89239657,
       -377.93926922, -365.53419424, -364.94925578, -355.46738394,
       -356.01317813, -353.70162336, -348.71781054, -344.51707622,
       -337.5861818 , -337.77130792, -333.28645836, -332.30589872,
       -328.06720686, -331.89338398, -332.18517299, -331.77878625,
       -334.89717474, -338.78815982, -342.52157007, -347.87153833,
       -357.67797757, -375.93496005, -382.28978728, -398.81521488,
       -406.94734854, -431.02461693, -437.75202985, -464.84577011,
       -466.57252973, -481.50392648, -487.39786506])

In [41]:
F=figure()
F.line(list(range(39)),Q[:39,:].sum(axis=1))
show(F)

In [42]:
Q[:39,:]

array([[-20.68707727, -19.85153896, -21.27634224, -22.8074935 ,
        -20.00174056, -20.0086531 , -20.27225349, -20.32914562,
        -20.37763871, -20.36501242, -21.50438801, -20.08815177,
        -19.50730511, -21.05554728, -21.15359243, -20.23519153,
        -20.34827178, -20.20432314, -17.36437575, -21.0015009 ],
       [-22.87703945, -23.36884132, -22.8870026 , -22.65544912,
        -23.53497417, -23.1681665 , -23.36517685, -24.30698574,
        -23.29899101, -23.64365848, -22.738666  , -23.69039222,
        -23.4665515 , -23.18631346, -23.72887776, -16.92027895,
        -22.50239792, -23.20697371, -23.73901454, -22.55850171],
       [-22.81662149, -22.48657065, -23.3358583 , -23.25000917,
        -22.85696733, -21.22989911, -21.51833406, -22.18609773,
        -21.5470101 , -22.18615072, -22.48929432, -15.9494979 ,
        -22.83861935, -21.73843565, -22.40872264, -22.90048959,
        -22.16329022, -21.981776  , -21.25166842, -22.28868283],
       [-22.29355892, -21.43661523, -

In [43]:
P=figure()
P.image(image=[Q[:39,:]], x=0, y=0, dw=10, dh=10, palette="Viridis256")

GlyphRenderer(id='p1203', ...)

In [44]:
show(P)

In [45]:
Q

array([[-2.06870773e+01, -1.98515390e+01, -2.12763422e+01, ...,
        -2.02043231e+01, -1.73643757e+01, -2.10015009e+01],
       [-2.28770395e+01, -2.33688413e+01, -2.28870026e+01, ...,
        -2.32069737e+01, -2.37390145e+01, -2.25585017e+01],
       [-2.28166215e+01, -2.24865707e+01, -2.33358583e+01, ...,
        -2.19817760e+01, -2.12516684e+01, -2.22886828e+01],
       ...,
       [ 2.15756674e-02,  2.37797087e-01,  7.69531677e-01, ...,
         2.30769887e-01,  7.86303664e-01,  4.04824999e-01],
       [ 3.08866911e-02,  6.19564520e-01,  8.25361812e-01, ...,
         4.51476665e-01,  2.19088568e-01,  2.27035462e-01],
       [ 1.29795628e-01,  9.31095617e-01,  1.88395033e-01, ...,
         9.51339361e-01,  8.08109201e-01,  3.09786562e-01]],
      shape=(100, 20))

In [46]:
I = np.load("2025-01-24_11-09-40/inventory_order_data.npy")

In [47]:
I

array([[ 392588.,  395678.,  396181., ...,  778715.,  778729., 1773813.],
       [  31506.,   29955.,   32644., ...,   37996.,   40315.,   34895.],
       [  29304.,   30486.,   31011., ...,   44565.,   42363.,   43941.],
       ...,
       [      0.,       0.,       0., ...,       0.,       0.,       0.],
       [      0.,       0.,       0., ...,       0.,       0.,       0.],
       [      0.,       0.,       0., ...,       0.,       0.,       0.]],
      shape=(100, 20))

In [48]:
I.shape

(100, 20)

In [49]:
I.sum(axis=1)

array([1.088687e+07, 8.526250e+05, 8.587940e+05, 8.607200e+05,
       8.541090e+05, 8.423520e+05, 8.237810e+05, 7.984020e+05,
       7.658140e+05, 7.319370e+05, 6.862340e+05, 6.386620e+05,
       5.813770e+05, 5.246570e+05, 4.767250e+05, 4.380640e+05,
       4.023240e+05, 3.592940e+05, 3.319500e+05, 2.970370e+05,
       2.851630e+05, 2.493900e+05, 2.269390e+05, 2.050360e+05,
       1.803210e+05, 1.441450e+05, 1.205960e+05, 1.112370e+05,
       9.723200e+04, 8.163400e+04, 6.350300e+04, 5.840200e+04,
       4.503100e+04, 3.589700e+04, 3.056300e+04, 2.246400e+04,
       1.889900e+04, 8.407000e+03, 3.413000e+03, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.0000

In [50]:
I

array([[ 392588.,  395678.,  396181., ...,  778715.,  778729., 1773813.],
       [  31506.,   29955.,   32644., ...,   37996.,   40315.,   34895.],
       [  29304.,   30486.,   31011., ...,   44565.,   42363.,   43941.],
       ...,
       [      0.,       0.,       0., ...,       0.,       0.,       0.],
       [      0.,       0.,       0., ...,       0.,       0.,       0.],
       [      0.,       0.,       0., ...,       0.,       0.,       0.]],
      shape=(100, 20))

In [51]:
I[:39,:]

array([[3.925880e+05, 3.956780e+05, 3.961810e+05, 3.984090e+05,
        4.009460e+05, 4.015400e+05, 4.083440e+05, 4.146460e+05,
        4.175170e+05, 4.255430e+05, 4.350730e+05, 4.457700e+05,
        4.611080e+05, 4.820750e+05, 5.186850e+05, 5.551900e+05,
        6.063200e+05, 7.787150e+05, 7.787290e+05, 1.773813e+06],
       [3.150600e+04, 2.995500e+04, 3.264400e+04, 3.178500e+04,
        3.167700e+04, 3.349300e+04, 3.227000e+04, 3.255600e+04,
        4.190700e+04, 3.664500e+04, 3.700400e+04, 3.633800e+04,
        1.613320e+05, 4.773200e+04, 4.844400e+04, 3.766300e+04,
        3.646800e+04, 3.799600e+04, 4.031500e+04, 3.489500e+04],
       [2.930400e+04, 3.048600e+04, 3.101100e+04, 3.035800e+04,
        3.208200e+04, 3.126400e+04, 3.256200e+04, 3.827800e+04,
        3.529800e+04, 3.542000e+04, 3.540600e+04, 3.247100e+04,
        1.815080e+05, 4.051000e+04, 3.625100e+04, 4.106700e+04,
        3.464900e+04, 4.456500e+04, 4.236300e+04, 4.394100e+04],
       [2.982900e+04, 3.014800e+04, 3

In [52]:
I[:40,:]

array([[3.925880e+05, 3.956780e+05, 3.961810e+05, 3.984090e+05,
        4.009460e+05, 4.015400e+05, 4.083440e+05, 4.146460e+05,
        4.175170e+05, 4.255430e+05, 4.350730e+05, 4.457700e+05,
        4.611080e+05, 4.820750e+05, 5.186850e+05, 5.551900e+05,
        6.063200e+05, 7.787150e+05, 7.787290e+05, 1.773813e+06],
       [3.150600e+04, 2.995500e+04, 3.264400e+04, 3.178500e+04,
        3.167700e+04, 3.349300e+04, 3.227000e+04, 3.255600e+04,
        4.190700e+04, 3.664500e+04, 3.700400e+04, 3.633800e+04,
        1.613320e+05, 4.773200e+04, 4.844400e+04, 3.766300e+04,
        3.646800e+04, 3.799600e+04, 4.031500e+04, 3.489500e+04],
       [2.930400e+04, 3.048600e+04, 3.101100e+04, 3.035800e+04,
        3.208200e+04, 3.126400e+04, 3.256200e+04, 3.827800e+04,
        3.529800e+04, 3.542000e+04, 3.540600e+04, 3.247100e+04,
        1.815080e+05, 4.051000e+04, 3.625100e+04, 4.106700e+04,
        3.464900e+04, 4.456500e+04, 4.236300e+04, 4.394100e+04],
       [2.982900e+04, 3.014800e+04, 3

In [53]:
I[:30,:]

array([[3.925880e+05, 3.956780e+05, 3.961810e+05, 3.984090e+05,
        4.009460e+05, 4.015400e+05, 4.083440e+05, 4.146460e+05,
        4.175170e+05, 4.255430e+05, 4.350730e+05, 4.457700e+05,
        4.611080e+05, 4.820750e+05, 5.186850e+05, 5.551900e+05,
        6.063200e+05, 7.787150e+05, 7.787290e+05, 1.773813e+06],
       [3.150600e+04, 2.995500e+04, 3.264400e+04, 3.178500e+04,
        3.167700e+04, 3.349300e+04, 3.227000e+04, 3.255600e+04,
        4.190700e+04, 3.664500e+04, 3.700400e+04, 3.633800e+04,
        1.613320e+05, 4.773200e+04, 4.844400e+04, 3.766300e+04,
        3.646800e+04, 3.799600e+04, 4.031500e+04, 3.489500e+04],
       [2.930400e+04, 3.048600e+04, 3.101100e+04, 3.035800e+04,
        3.208200e+04, 3.126400e+04, 3.256200e+04, 3.827800e+04,
        3.529800e+04, 3.542000e+04, 3.540600e+04, 3.247100e+04,
        1.815080e+05, 4.051000e+04, 3.625100e+04, 4.106700e+04,
        3.464900e+04, 4.456500e+04, 4.236300e+04, 4.394100e+04],
       [2.982900e+04, 3.014800e+04, 3

In [54]:
P=figure()
P.image(image=[I[:39,:]], x=0, y=0, dw=10, dh=10, palette="Viridis256")

GlyphRenderer(id='p1255', ...)

In [55]:
show(P)

In [56]:
Q[1][2]

np.float64(-22.88700260172461)

In [57]:
Q[1,2]

np.float64(-22.88700260172461)

In [59]:
np.max(Q[1,:])

np.float64(-16.92027894612226)

In [61]:
np.where(Q[1,:]==np.max(Q[1,:]))[0]

array([15])

In [63]:
V

array([-17.0167396 , -17.00540148, -16.41980477, -16.38524058,
       -15.69136931, -15.46131583, -14.93477731, -15.10286624,
       -14.57774065, -14.52378531, -14.55342079, -13.98632692,
       -13.79323355, -14.13836364, -13.36918428, -13.53559532,
       -13.35789276, -13.48585142, -13.39865367, -13.65060903,
       -13.72129892, -14.07155259, -13.77614154, -13.69893515,
       -13.97534257, -14.11639242, -14.42558957, -14.47266216,
       -14.81057455, -15.14099419, -14.96618101, -15.89105146,
       -15.96624877, -16.71790262, -16.90306477, -17.74073421,
       -18.26177638, -17.9588335 , -19.3316213 ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.        ,
         0.        ,   0.        ,   0.        ,   0.  

In [64]:
V[:39,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [65]:
V[:39]

array([-17.0167396 , -17.00540148, -16.41980477, -16.38524058,
       -15.69136931, -15.46131583, -14.93477731, -15.10286624,
       -14.57774065, -14.52378531, -14.55342079, -13.98632692,
       -13.79323355, -14.13836364, -13.36918428, -13.53559532,
       -13.35789276, -13.48585142, -13.39865367, -13.65060903,
       -13.72129892, -14.07155259, -13.77614154, -13.69893515,
       -13.97534257, -14.11639242, -14.42558957, -14.47266216,
       -14.81057455, -15.14099419, -14.96618101, -15.89105146,
       -15.96624877, -16.71790262, -16.90306477, -17.74073421,
       -18.26177638, -17.9588335 , -19.3316213 ])

In [66]:
V[:39].max()

np.float64(-13.35789275598864)

In [67]:
np.argmax(V[:39])

np.int64(16)

In [68]:
Q=np.load("2025-01-24_11-42-45/q_table.npy")

In [69]:
Q[:39,:]

array([[-20.94140712, -20.34941078, -20.20768136, -20.60951454,
        -20.47065067, -19.8277491 , -20.69487035, -21.41383732,
        -20.37554782, -20.32273584, -20.36715224, -19.63187929,
        -20.7676464 , -20.54381332, -20.27865456, -20.39519627,
        -20.55811267, -20.35239454, -17.01681402, -20.36346126],
       [-24.66262134, -23.01092813, -23.22889047, -24.67373585,
        -22.64852378, -24.09027843, -23.22156004, -22.82554903,
        -24.96161421, -22.96842164, -23.61918124, -23.20746716,
        -21.76112209, -23.75597073, -23.43036219, -22.7940182 ,
        -22.59345596, -23.14797923, -17.00554746, -23.47975994],
       [-23.03236148, -22.24150197, -22.86956485, -23.35959153,
        -23.61015132, -23.23712072, -22.71288936, -22.19279118,
        -22.9079216 , -22.68793343, -22.56445483, -21.01424324,
        -22.51506489, -23.15913767, -23.28664234, -22.98258837,
        -23.7284638 , -22.23204404, -23.12432285, -16.41993179],
       [-22.65054573, -21.68424228, -

In [70]:
Q.sum(axis=1)

array([-405.48852947, -461.0869871 , -449.87872126, -439.75474633,
       -425.00910368, -408.86730782, -399.90483864, -394.89690519,
       -383.95879213, -365.3823123 , -366.9311194 , -360.10793635,
       -359.13830406, -349.57085943, -350.64930457, -340.24639329,
       -339.47450696, -331.15216636, -339.28775351, -331.31413965,
       -323.83939638, -330.61331388, -329.36043334, -326.85170325,
       -330.97071591, -333.19195093, -340.61773531, -347.8905932 ,
       -353.94558881, -361.87112411, -378.16529295, -393.62584564,
       -400.55526974, -410.69945958, -428.96860514, -454.66380751,
       -457.48266622, -478.14518453, -495.59796832,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.     

In [72]:
np.argmax(Q[:39].sum(axis=1))

np.int64(20)

In [73]:
Q.shape

(100, 20)

In [74]:
Q

array([[-20.94140712, -20.34941078, -20.20768136, ..., -20.35239454,
        -17.01681402, -20.36346126],
       [-24.66262134, -23.01092813, -23.22889047, ..., -23.14797923,
        -17.00554746, -23.47975994],
       [-23.03236148, -22.24150197, -22.86956485, ..., -22.23204404,
        -23.12432285, -16.41993179],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]], shape=(100, 20))

In [75]:
Q= np.load("2025-01-24_11-56-40/q_table.npy")

In [76]:
Q

array([[-19.86618444, -19.84030689, -20.69784695, ..., -19.76784064,
        -19.79347632, -16.64321062],
       [-22.8082004 , -22.46162404, -23.17905792, ..., -21.93512264,
        -22.32509689, -16.72034944],
       [-22.85079153, -21.43199986, -22.42486729, ..., -16.26089925,
        -22.40248422, -23.97397367],
       ...,
       [-50.        , -50.        , -50.        , ..., -50.        ,
        -50.        , -50.        ],
       [-50.        , -50.        , -50.        , ..., -50.        ,
        -50.        , -50.        ],
       [-50.        , -50.        , -50.        , ..., -50.        ,
        -50.        , -50.        ]], shape=(100, 20))

In [77]:
P=figure()
P.image(image=[Q[:39,:]], x=0, y=0, dw=10, dh=10, palette="Viridis256")
show(P)

In [78]:
Q[0,:]

array([-19.86618444, -19.84030689, -20.69784695, -19.87755421,
       -19.81351517, -20.74429397, -20.53755746, -21.06480198,
       -20.05844726, -19.9013108 , -19.80976229, -20.72545974,
       -21.13951271, -19.56527843, -19.49597325, -19.99187079,
       -19.92211519, -19.76784064, -19.79347632, -16.64321062])

In [79]:
Q[1,:]

array([-22.8082004 , -22.46162404, -23.17905792, -20.97909902,
       -23.41100026, -22.33170111, -22.60006562, -22.9434552 ,
       -22.39625365, -23.0121246 , -22.58914192, -23.42391903,
       -23.02518558, -21.90914329, -23.22175304, -22.45675453,
       -22.18352964, -21.93512264, -22.32509689, -16.72034944])

In [90]:
F=figure()
F.line(list(range(20)),Q[8,:])
show(F)

In [91]:
np.argmax(Q,axis=1)

array([19, 19, 17, 17,  5, 19, 17, 10, 18, 14,  9,  5,  5,  9, 15, 16, 17,
       10,  9, 10, 16,  6, 10,  2,  9,  5,  3,  7, 10,  3,  5,  4, 15,  7,
        4, 18, 17,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [92]:
np.argmax(Q,axis=0)

array([17, 19, 23, 29, 31, 12, 21, 27, 14, 18, 19, 19, 16, 20,  9, 14, 20,
       16,  8,  5])

In [100]:
Q = np.load("2025-01-24_12-21-38/q_table.npy")

In [101]:
Q

array([[-11.60741575, -10.93626684, -11.68364191, -10.81281561,
        -10.30181208, -10.76432595, -10.18715027, -10.77295255,
        -10.50652254, -10.63019925, -10.77251883, -11.30156084,
        -11.41886206, -10.20035173, -11.4758572 , -12.52459861,
         -8.01368748, -10.22735897, -10.71142919, -12.34320111],
       [-10.97564889, -11.94434326, -11.39214715, -11.75889507,
        -11.32161953, -11.18182228, -10.74750378, -10.95805149,
        -11.44492309, -11.57446525, -11.65824873, -11.61398627,
        -11.03873755, -11.46700264, -10.85440283,  -6.89999869,
        -11.15545905, -11.09308018, -11.0308812 , -11.52258399],
       [-10.97187517, -11.50680511, -10.90289032, -10.35319426,
         -6.61751693, -10.72796101, -11.92930102,  -9.79143065,
        -11.80499677, -10.91767862, -10.60934165, -10.89495147,
        -10.47955531, -10.77703888, -10.5828977 , -14.08577993,
        -10.94738624, -11.25431919, -11.00836375, -10.61185019],
       [-10.48345467, -10.61322007, -

In [102]:
Q[0,:]

array([-11.60741575, -10.93626684, -11.68364191, -10.81281561,
       -10.30181208, -10.76432595, -10.18715027, -10.77295255,
       -10.50652254, -10.63019925, -10.77251883, -11.30156084,
       -11.41886206, -10.20035173, -11.4758572 , -12.52459861,
        -8.01368748, -10.22735897, -10.71142919, -12.34320111])

In [103]:
Q[1,:]

array([-10.97564889, -11.94434326, -11.39214715, -11.75889507,
       -11.32161953, -11.18182228, -10.74750378, -10.95805149,
       -11.44492309, -11.57446525, -11.65824873, -11.61398627,
       -11.03873755, -11.46700264, -10.85440283,  -6.89999869,
       -11.15545905, -11.09308018, -11.0308812 , -11.52258399])

In [104]:
np.argmax(Q,axis=1)

array([16, 15,  4, 13, 13,  5, 18, 16, 14, 13, 16, 19, 18, 18,  8, 18, 15,
       14, 11, 15,  7, 15, 15,  6, 14, 17,  8,  3, 15,  7,  0,  4, 15,  4,
        3,  2,  3,  3,  5,  0])

In [113]:
Q = np.load("2025-01-24_12-33-26/q_table.npy")
F=figure()
F.line(list(range(Q[:39].shape[0])),np.argmax(Q,axis=1))
show(F)

In [114]:
show(F)

In [108]:
H = np.argmax(Q,axis=1)

In [112]:
F=figure()
F.line(list(range(Q[:39].shape[0])),Q.sum(axis=1))
show(F)

In [115]:
from scipy.special import softmax

In [117]:
Qs=softmax(Q[:39],axis=1)

In [118]:
Qs.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [119]:
P=figure()
P.image(image=[Qs], x=0, y=0, dw=10, dh=10, palette="Viridis256")
show(P)

In [120]:
Q = np.load("2025-01-24_14-14-09/q_table.npy")

In [121]:
softmax(Q,axis=1)

array([[1.37141472e-06, 6.07124785e-06, 1.01600483e-05, 3.18478958e-06,
        2.58627832e-06, 3.59562661e-06, 1.36405274e-06, 3.21686628e-06,
        1.36479887e-05, 6.32042533e-07, 1.18667735e-06, 1.63628068e-06,
        2.58236800e-06, 3.43713579e-06, 1.16799863e-06, 2.73136807e-06,
        7.73902527e-06, 5.21739504e-06, 6.07222374e-06, 9.99922399e-01],
       [8.42740525e-04, 3.56124050e-04, 9.89834581e-01, 1.21410580e-04,
        4.04672454e-04, 1.83907116e-04, 1.53953025e-04, 2.16735127e-03,
        1.09568109e-04, 1.41720612e-04, 4.95486692e-04, 1.73227602e-03,
        3.58347666e-04, 6.45430416e-04, 1.36414193e-04, 1.36302580e-04,
        3.24343114e-04, 6.88276125e-04, 8.16511914e-04, 3.50582745e-04],
       [1.58894175e-04, 4.39801714e-04, 1.94213301e-04, 8.74912311e-05,
        6.61148526e-04, 3.64358424e-04, 2.61588771e-04, 2.58535996e-04,
        3.61513535e-01, 2.64743334e-04, 1.18040876e-04, 1.13758346e-04,
        6.33728422e-01, 1.45931868e-04, 1.38679440e-04, 2.5985

In [122]:
softmax(Q[:39,:],axis=1)

array([[1.37141472e-06, 6.07124785e-06, 1.01600483e-05, 3.18478958e-06,
        2.58627832e-06, 3.59562661e-06, 1.36405274e-06, 3.21686628e-06,
        1.36479887e-05, 6.32042533e-07, 1.18667735e-06, 1.63628068e-06,
        2.58236800e-06, 3.43713579e-06, 1.16799863e-06, 2.73136807e-06,
        7.73902527e-06, 5.21739504e-06, 6.07222374e-06, 9.99922399e-01],
       [8.42740525e-04, 3.56124050e-04, 9.89834581e-01, 1.21410580e-04,
        4.04672454e-04, 1.83907116e-04, 1.53953025e-04, 2.16735127e-03,
        1.09568109e-04, 1.41720612e-04, 4.95486692e-04, 1.73227602e-03,
        3.58347666e-04, 6.45430416e-04, 1.36414193e-04, 1.36302580e-04,
        3.24343114e-04, 6.88276125e-04, 8.16511914e-04, 3.50582745e-04],
       [1.58894175e-04, 4.39801714e-04, 1.94213301e-04, 8.74912311e-05,
        6.61148526e-04, 3.64358424e-04, 2.61588771e-04, 2.58535996e-04,
        3.61513535e-01, 2.64743334e-04, 1.18040876e-04, 1.13758346e-04,
        6.33728422e-01, 1.45931868e-04, 1.38679440e-04, 2.5985

In [123]:
Q[:40,:]

array([[-40.99738491, -39.5096636 , -38.99476457, -40.15484154,
        -40.36300786, -40.03350948, -41.00276753, -40.14482008,
        -38.6996356 , -41.77202635, -41.1420705 , -40.82080197,
        -40.36452095, -40.07858926, -41.15793605, -40.30842515,
        -39.26695202, -39.66122952, -39.50950287, -27.49779481],
       [-35.08423782, -35.9456178 , -28.01560381, -37.0217189 ,
        -35.81781895, -36.6064661 , -36.78424941, -34.13963584,
        -37.12435058, -36.86703933, -35.61535643, -34.36370549,
        -35.93939328, -35.35097952, -36.90520113, -36.90601966,
        -36.03909498, -35.28670683, -35.11585543, -35.96130018],
       [-35.36944563, -34.35136007, -35.168727  , -35.96614547,
        -33.94370553, -34.53954598, -34.87091035, -34.88264911,
        -27.63962928, -34.85892324, -35.66665307, -35.70360761,
        -27.07830826, -35.45454419, -35.50551896, -34.87755066,
        -34.78340773, -33.7644918 , -35.31005701, -36.60997594],
       [-34.884624  , -34.20318503, -